### PR TITLE
Add the class "dataframe"

### PR DESCRIPTION
**Pull request by ramnathv**
This will pretty-print the tables as a nice table with striped rows.

### CODE REVIEW

**Comment by flying-sheep** [comment]
ah cool, where? jupyter lab? notebook? vs code?

**Comment by ramnathv** [comment]
@flying-sheep Sorry, I realized much later that this class is required on Google Colab for pretty-printing  R data frames just like pandas data frames. For regular Jupyter Notebooks, the display is already nice!

**Comment by flying-sheep** [comment]
OK! Just fix the tests and I’ll merge it

**Comment by flying-sheep** [comment]
Seems like it, weird. Thank you for the contribution!

**Pull request merged**
