### PR TITLE
Add factor repr with levels

### LINKED ISSUE #84: Factor variable printout is missing level context
For example, these both appear about the same in the notebook:
```r
library(forcats)
mth = month.name

as.factor(mth)
```
```
     January February March April May June July August September October November December 
```
```r
as_factor(mth)
```
```
     January February March April May June July August September October November December 
```
as do these:
```r
mth2 <- c(mth[10:12], mth[6:12], mth)
mth2
```
```
     'October' 'November' 'December' 'June' 'July' 'August' 'September' 'October' 'November' 'December' 'January' 'February' 'March' 'April' 'May' 'June' 'July' 'August' 'September' 'October' 'November' 'December' 
```
```r
fct_infreq(mth2)
```
```
     October November December June July August September October November December January February March April May June July August September October November December 
```
```r
fct_inorder(mth2)
```
```
     October November December June July August September October November December January February March April May June July August September October November December
```
But in an R console, it prints out the levels, so it's clear that these produce different results:
```r
> library(forcats)
> mth = month.name
> as.factor(mth)
 [1] January   February  March     April     May       June      July     
 [8] August    September October   November  December 
12 Levels: April August December February January July June March ... September
> as_factor(mth)
 [1] January   February  March     April     May       June      July     
 [8] August    September October   November  December 
12 Levels: January February March April May June July August ... December


> mth2 <- c(mth[10:12], mth[6:12], mth)
> mth2
 [1] "October"   "November"  "December"  "June"      "July"      "August"   
 [7] "September" "October"   "November"  "December"  "January"   "February" 
[13] "March"     "April"     "May"       "June"      "July"      "August"   
[19] "September" "October"   "November"  "December" 
> fct_infreq(mth2)
 [1] October   November  December  June      July      August    September
 [8] October   November  December  January   February  March     April    
[15] May       June      July      August    September October   November 
[22] December 
12 Levels: December November October August July June September ... May
> fct_inorder(mth2)
 [1] October   November  December  June      July      August    September
 [8] October   November  December  January   February  March     April    
[15] May       June      July      August    September October   November 
[22] December 
12 Levels: October November December June July August September ... May
```

Ported from IRkernel/IRkernel#456.

### PR DESCRIPTION
**Pull request by flying-sheep**
fixes #84.

@QuLogic, are you happy with those reprs?

### CODE REVIEW

**Comment by QuLogic** [comment]
I _think_ it might look okay, but I'm not sure how to install a development version from here.

**Comment by flying-sheep** [comment]
[`devtools::install_github('IRkernel/repr')`](https://irkernel.github.io/installation/#devel-panel)

**Comment by QuLogic** [comment]
OK, would be nice if that expander used a pointer cursor, but otherwise looks pretty good to me.

**Comment by flying-sheep** [comment]
OK, let’s see if the tests pass.

**Pull request merged**
