### PR TITLE
Also generate png/jpg with png and jpeg capabilities

### PR DESCRIPTION
**Pull request by takluyver**
Fixes gh-11

It would be nice to do a new release fairly soon after this, because plots don't currently show up on Windows.

Ping @asmeurer

### CODE REVIEW

**Comment by flying-sheep** [comment]
let’s make @asmeurer confirm this and then pull & release immediately, as i doubt this can cause any problem.

**Comment by JanSchulz** [comment]
Just FYI: I'm not available until the weekend...

**Comment by JanSchulz** [comment]
Also: wouldn't it be easier to simple wrap the image generation in a `try...` block and remove all capability checks?

**Comment by rgbkrk** [comment]
Looks good to me.

**Comment by takluyver** [comment]
@JanSchulz @asmeurer, I've tagged 0.3, please start your respective release processes whenever it's convenient. :-)

**Comment by JanSchulz** [comment]
https://github.com/IRkernel/irkernel.github.io/pull/15/

**Comment by JanSchulz** [comment]
Not sure who builds the macosx ones now :-/

**Comment by rgbkrk** [comment]
I'm happy to run OS X builds if you like. How would you feel about builds on [Travis using OS X workers](http://docs.travis-ci.com/user/osx-ci-environment/)?

**Comment by JanSchulz** [comment]
@rgbkrk I would like that very much! :-) Is there a way to generate the build from say a PR which includes the source package? Windows builds could be done via winbuilder (http://win-builder.r-project.org/upload.aspx)

**Comment by JanSchulz** [comment]
@rgbkrk There are build instructions in https://github.com/IRkernel/irkernel.github.io/blob/master/adding_releases.md if you need them :-)

**Comment by rgbkrk** [comment]
Alright, trying it out now.

```
$ R CMD build repr
* checking for file ‘repr/DESCRIPTION’ ... OK
* preparing ‘repr’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘repr_0.3.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'
```

Is that going ok? Maybe as I understand how the R stuff is laid out we can script this and the "token Mac" can build it.

**Comment by rgbkrk** [comment]
```
$ R CMD check repr*.tar.gz
* using log directory ‘/Users/kyle6475/code/IRkernel/repr.Rcheck’
* using R version 3.2.1 (2015-06-18)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘repr/DESCRIPTION’ ... OK
* this is package ‘repr’ version ‘0.3’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Package suggested but not available: ‘highr’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE

Status: 1 ERROR
See
  ‘/Users/kyle6475/code/IRkernel/repr.Rcheck/00check.log’
for details.
```

**Comment by rgbkrk** [comment]
:boom: Installed highr and it cranked along.

Oh wait.

```
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -rf /var/folders/ps/1dvr90bd6p3blnyrnpyxnryhv45qg1/T//RtmpHhym2V/Rd2pdf10f0d4f58470e'
* DONE

Status: 1 ERROR, 1 WARNING, 1 NOTE
See
  ‘/Users/kyle6475/code/IRkernel/repr.Rcheck/00check.log’
for details.
```

I don't have LaTeX on this Mac. :( Ok, I'll come back to this after some installs.

**Comment by flying-sheep** [comment]
ah yeah, binary packages build the PDF version of the manual.

if you want to speed up tests if it works, just use `R CMD Rd2pdf .` inside the package directory instead of re-running `R CMD CHECK` all the time. once that works, you should be able to build.

**Pull request merged**
