### PR TITLE
Fun with Travis builds

### PR DESCRIPTION
**Pull request by karldw**
Working on tests (#5).

In line 25, I'm not sure whether it's correct to use `libjpeg`, `libjpeg-dev` or neither.  The Cairo documentation says it needs some kind of jpeg backend to work with jpeg formats.

We might also need to add gcc, g++ or gfortran to the apt package list.  Let's see how the build goes without them.

### CODE REVIEW

**Comment by flying-sheep** [comment]
flicked the switch. let’s see if we can trigger travis by closing and reopening this.

**Comment by flying-sheep** [comment]
> Error in library(data.table) : there is no package called 'data.table'

yo

**Comment by karldw** [comment]
> does R have `devDevendencies` or so?

[As far as I know](http://r-pkgs.had.co.nz/description.html#dependencies), these just go in the `Suggests` section of the DESCRIPTION file.  Cairo and highr are already there; am I missing any others?

I have no idea why the build failed.  Looking at the [full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/114199548/log.txt), data.table was installed successfully.  Could you try toggling this pull request again to see if it's some weird [one-off](https://github.com/travis-ci/travis-ci/issues/5650)/cache issue?

**Comment by karldw** [comment]
Never mind, the Travis build still fails on `library(data.table)` with my more recent commits, so no need to toggle this request open and closed.

**Comment by flying-sheep** [comment]
by the way, you can toggle it yourself by closing/reopening.

**Comment by karldw** [comment]
Thanks!  Any idea why the build fails?

**Comment by JanSchulz** [comment]
https://stackoverflow.com/questions/21380288/loading-the-testthat-package-only-for-tests-but-not-requiring-in-dependencies ?

**Comment by flying-sheep** [comment]
can you check where the data.table package ended up and what `.libPaths()` is in the tests?

**Comment by JanSchulz** [comment]
Another work around, which might work on travis but will give problems when run during the cran submission or locally: add a r call which installs the package before running the script and then load the data.table package (or use a direct call: `data.table::function_call(...)`). Maybe wrap the test in a something which checks if a package is available?

```R
if (requireNamespace('data.table', quietly = TRUE)) {
  require("data.table")
  # test which requires data.table and which loads the package first
}
```
[+ the data.table install via an R call in the travis file]

**Comment by karldw** [comment]
The packages (or at least data.table) get installed in /home/travis/R/Library, but .libPaths() gives:
- "/tmp/RtmpKaVLfp/RLIBS_311c14cef1bd" 
- "/home/travis/R-bin/lib/R/library" 

We can work around this, but it seems like a problem in Travis's behavior.

**Comment by flying-sheep** [comment]
definitely

**Comment by JanSchulz** [comment]
There is now a fix in https://github.com/karldw/repr/pull/1

**Comment by karldw** [comment]
Here's the previous, successful build with jimhester's changes: https://travis-ci.org/IRkernel/repr/builds/115547433
Here's another build, after toggling the pull request open and closed: https://travis-ci.org/IRkernel/repr/builds/115549468

Caching works!  (Though it seems like they're doing a separate cache for each PR.)

**Comment by flying-sheep** [comment]
real great!

it would be nice if you could add a `Enhances: data.table, dplyr` field in addition to the `Suggests:` field.

**Comment by takluyver** [comment]
@flying-sheep is there anything further you think this needs before we merge it?

**Comment by flying-sheep** [comment]
nope, i just didn’t see that @karldw did the last thing

**Comment by flying-sheep** [comment]
oh and many thanks in your direction @karldw! you’re so awesome!

**Comment by takluyver** [comment]
Yep, definite kudos for setting this up :tada:

**Pull request merged**
