### PR TITLE
Add type headers and captions

### LINKED ISSUE #113: Feature request: display column type and dimensions
This is in reference to #112.

With the **tibbles** package in R when you print out a tibble you get:
 * Output truncated to the first 10 rows and however many columns fit on the page
 * The typing of each column's values
 * The dimensions of the full tibble

Currently when I print out a tibble in Jupyter notebooks I get the full output as well, formatted the same as if it was a data frame. Based on #112 that is by design, but it would be nice to be able to get the typing and dimensions as well.

### PR DESCRIPTION
**Pull request by flying-sheep**
Ha, this should work! Hi @aguang, wanna give this a test ride?

This PR makes repr more tibble-like, adding column types to each data.frame column, and one central type to the caption.

There’s two potential issues:

1. The tests probably fail on Windows because of the unicode “×” (fixable in the `expect_id_text` function).
2. I didn’t properly implement LaTeX table captions, because we’re not in a float (`\begin{table}`), so I should probably add `\captionof{table}{...}` (which however needs the caption package. Hmm)

Fixes #113

### CODE REVIEW

**Comment by aguang** [comment]
Sure, do I do `devtools::install_github(repo="IRkernel/repr", ref="types")`?

**Comment by flying-sheep** [comment]
exactly!

**Comment by flying-sheep** [comment]
Hi @aguang does it work well? No issues found?

**Comment by bosbes** [comment]
I upgraded R and now have these captions in the output in Jupyter notebooks. Is it possible to disable them?

**Comment by flying-sheep** [comment]
Not currently, but an option can be added. Why do you want to?

**Comment by bosbes** [comment]
I use Jupyter notebooks to present my research to non-programmers. The caption with "a data frame 6 x 3" look out of place in that context. If there is a workaround/hack to get the captionless table back, I would be happy with that too. I would prefer to keep display logic out of my notebooks as much as possible.

**Comment by flying-sheep** [comment]
Well, you just need to modify `repr_matrix_generic` so it has an option to suppress types.

1. You need to add a branch here that intercepts that option and doesn’t modify the header if the option is set:

     https://github.com/IRkernel/repr/blob/d25aad07474644a38bd146ad82ee29dd857de4e3/R/repr_matrix_df.r#L171-L172

     And you need to create a branch here that leaves the caption empty if that option is set:

     https://github.com/IRkernel/repr/blob/d25aad07474644a38bd146ad82ee29dd857de4e3/R/repr_matrix_df.r#L207-L208

2. Then you need to change `repr_matrix_generic` so that it doesn’t just have the `wrap` argument, but also a `wrap_caption` one. E.g. in `repr_html.matrix`,

     ```r
     wrap = '<table>\n<caption>%s</caption>\n%s%s</table>\n',
     ```

    would become

     ```r
     wrap = '<table>\n%s%s%s</table>\n', wrap_caption = '<caption>%s</caption>\n',
     ```

3. You need to add tests to make sure your changes work and don’t break anything.

**Pull request merged**
