### PR TITLE
Accommodate data.table's column indexing.

### PR DESCRIPTION
**Pull request by karldw**
The `ellip.limit.arr` function indexes columns by number in a couple of places, which is perfectly fine for `data.frame`s, but doesn't work with `data.table`s.  To avoid this hassle, I've added a line to convert from `data.table`s to `data.frame`s.  (An alternative would be to use `with=FALSE` for data.tables, but that would require a lot of `if` statements.  See http://stackoverflow.com/a/28094726.)

### CODE REVIEW

**Comment by flying-sheep** [comment]
this requires the other PR.

either we merge that first or you do the following to clean this PR

```git
git checkout datatable_compat
git reset --hard master
git cherry-pick 88d68b2
git push -f
```

**Comment by karldw** [comment]
I'd be happy to do the cherry-picking, or just wait until #23 is resolved, whatever's easiest for you.

**Comment by flying-sheep** [comment]
i don’t care :smile:

**Comment by flying-sheep** [comment]
OK, so this one is simply 88d68b28974e256ae1b92e3c161f46e7309336d8, right? can you rebase this onto master?

**Pull request closed without merging**
