### PR TITLE
Add more plot methods to do plots besides cairo

### LINKED ISSUE #122: Error displaying builtin datasets
Trying to display some builtin datasets in a jupyter cell like `Nile` or `AirPassengers` causes an error: 
```
ERROR while rich displaying an object: Error in repr_matrix_generic(obj, "\n%s%s\n", sprintf("|%%s\n|%s|\n", : formal argument "cols" matched by multiple actual arguments

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_markdown.ts(obj)
9. repr_ts_generic(obj, repr_markdown.matrix, ...)
10. repr_func(m, ..., rows = nrow(m), cols = ncol(m))
```

How to fix this?

```
R versions: 
r-base 3.6.1
r-repr 0.19.2
jupyterlab 1.2.0a0
```

By the way, in the running `AirPassengers` still shows the dataframe at the end of the error message, as attached, while running `Nile` does not show anything.
image

### PR DESCRIPTION
**Pull request by flying-sheep**
But i’m not sure if `capabilities('png')` really means that `png(..., type = 'Xlib)` works.

if `type = 'Xlib'` means something else, what does `capabilities('png')` mean?

does it mean we have to manually use e.g. `quartz(...)` on a device with `capabilities('png') == FALSE`?

might fix #122

### CODE REVIEW

**Comment by JanSchulz** [comment]
Do we have to add the type? The [help](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/png.html) says: 
> The default is set by getOption("bitmapType") – the ‘out of the box’ default is "quartz" or "cairo" where available, otherwise "Xlib"

**Comment by flying-sheep** [comment]
well, does `capability("png")` really mean what it says on the tin?

because `quartz` says that if it’s available, it is be used as `png` backend… why would  `png()` not work if `quartz` is available?

**Comment by JanSchulz** [comment]
Oups, just looked at the source code (which hardcode one type) and not on the capabilities thingy in https://github.com/IRkernel/IRkernel/issues/122. 

Hm, can't we do a try-catch?

**Comment by flying-sheep** [comment]
nope, `png(..., type='quartz')` works on my decidedly non-apple PC. i assume it falls back to something else then?

**Comment by flying-sheep** [comment]
so i think this is it. will fix many plot-related boogs

**Pull request merged**
