### PR TITLE
Convert date columns in data frames to strings before displaying

### PR DESCRIPTION
**Pull request by takluyver**
Can't insert ellipsis into a date column.

Closes IRkernel/IRkernel#223

### CODE REVIEW

**Comment by rsmith31415** [comment]
I tested and works correctly in the example in IRkernel/IRkernel#223.

**Comment by takluyver** [comment]
Thanks! I'd like @flying-sheep to take a quick look at this, but it should be good to go.

**Comment by flying-sheep** [comment]
looks good!

**Comment by rsmith31415** [comment]
Great. Thanks!

**Pull request merged**
