### PR TITLE
Fix for dev stringr

### PR DESCRIPTION
**Pull request by hadley**
Where `str_view()` now prefers a console display that uses cli for colouring

### CODE REVIEW

**Comment by flying-sheep** [comment]
Doesn’t work with the current version:

```
Error in `stringr::str_view("xy", "y", html = TRUE)`: unused argument (html = TRUE)
```

So either repr has to wait for the new stringr to get released or we make the code forward compatible without breaking compatibility with the current version.

You could just do a patch release 1.4.2 for stringr that accepts `html = TRUE` and throws an error on `html = FALSE`, then we can change the dependency version of repr to `>= 1.4.2` and release a forward-compatible repr version before stringr 1.5 comes out.

**Comment by flying-sheep** [comment]
Ah right, didn’t notice this was just tests!

Sure, I’ll merge this once the new version is out, if that happens soon enough that I remember why I subscribed to tidyverse/stringr releases.

Thank you for helping out with the reverse deps!

**Comment by hadley** [comment]
This patch should work regardless of the version of stringr, so you can merge/release whenever.

I haven't official kicked off the stringr release process, but I'll ping this PR when I do (unless it's obvious that an updated repr is already on CRAN).

**Comment by hadley** [comment]
FYI stringr is now scheduled for release to CRAN on Dec 2.

**Comment by flying-sheep** [comment]
thank you for the info!

**Pull request merged**
