### PR TITLE
Fix R CMD check things

### PR DESCRIPTION
**Pull request by janschulz**
* fix listing of authors
* document undocumented parameters (hey, @flying-sheep that was one of yours! :-)
* regenerate doumentation
* make a note about quartz disapear
* document the leftover: one WARNING and one NOTE

### CODE REVIEW

**Comment by janschulz** [comment]
Maybe we should add a test on travis, that runs R CMD check and ensure that the number of warnings/NOTES does not increase...

**Comment by flying-sheep** [comment]
it’s done automatically but we had warnings being fatal turned off: a64c60d76bd01a060a21fa689540681fcae459a7

**Comment by janschulz** [comment]
Maybe do a manual test ala `grep "NOTE" <log> | wc -l | <whatever makes this fail if it is not 3 (and 2 after the first upload)`

**Comment by flying-sheep** [comment]
ATM there’s only 1 note AFAICS

**Comment by janschulz** [comment]
The second note (after your fixes) was from the "Initial release" stuff, if that's not in the travis build, that's fine :-)

Your idea looks good!

**Pull request merged**
